name: "retrieve and filter data"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs workflow at 12:00am every day
jobs:
  # updates the local CSV file
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download updated trip updates file
        run: pwd && curl "https://cdn.mbta.com/realtime/TripUpdates_enhanced.json" > ./src/lib/data/new_trip_updates.json
      # https://github.com/actions/setup-python
      - name: "Use Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      - name: Print working directory
        run: pwd
      - name: List files in src/lib
        run: ls -la ./src/lib
      - name: Run Python script
        working-directory: ./src/lib
        run: python parse-data.py
      - name: Set Git Config
        run: git config user.name 'github-actions[bot]' &&
            git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Push updated file onto main branch
        run: git add .
      - name: Git commit if there are new changes
        run: git commit -m "Updating and parsing data."
      - name: Push to origin/main
        run: git push
