name: "retrieve and filter data"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs workflow at 12:00am every day
jobs:
  # updates the local CSV file
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Download updated trip updates file"
        run: pwd && curl "https://cdn.mbta.com/realtime/TripUpdates_enhanced.json" > ./src/lib/data/trip_updates.json
      # https://github.com/actions/setup-python
      - name: "Use Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      - name: "Run Python script"
        run: python ./src/lib/parse_data.py